# Generated by Django 3.2.18 on 2023-03-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['dish_type'], 'verbose_name_plural': 'dishes'},
        ),
    ]
